### ISSUE TITLE
RFC logo: penguin listens to some beats

### ISSUE THREAD

**Issue by jochenklein** [africanpenguin/jukebox#1]
![penguinjukebox](https://cloud.githubusercontent.com/assets/5556084/8132491/6b2c38c0-1122-11e5-9174-0d147ce44daf.png)

**Comment by bouzlibop** [comment]
:+1:

**Comment by jochenklein** [comment]
ping @africanpenguin/developers

**Comment by crepererum** [comment]
ACK

**Comment by crepererum** [comment]
Hold for vectorized version...

**Comment by jochenklein** [comment]
:+1:
